create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  institution text,
  product_type text,
  remaining_debt numeric(14, 2) not null default 0,
  minimum_payment numeric(14, 2),
  rate numeric(8, 4),
  due_day integer,
  constraint debts_remaining_debt_nonnegative check (remaining_debt >= 0),
  constraint debts_minimum_payment_nonnegative check (
    minimum_payment is null or minimum_payment >= 0
  ),
  constraint debts_rate_nonnegative check (rate is null or rate >= 0),
  constraint debts_due_day_valid check (
    due_day is null or (due_day >= 1 and due_day <= 31)
  )
);

create table if not exists public.cash (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  balance numeric(14, 2) not null default 0,
  note text,
  constraint cash_balance_nonnegative check (balance >= 0)
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  debt_id bigint not null references public.debts(id) on delete restrict,
  cash_id bigint not null references public.cash(id) on delete restrict,
  amount numeric(14, 2) not null,
  note text,
  constraint payments_amount_positive check (amount > 0)
);

create index if not exists payments_debt_id_idx on public.payments (debt_id);
create index if not exists payments_cash_id_idx on public.payments (cash_id);
